const crypto = require("crypto");
const supabase = require("../config/supabase");

const STORAGE_BUCKET = process.env.SUPABASE_STORAGE_BUCKET || "teacher-documents";
const MAX_UPLOAD_BYTES = parseInt(process.env.MAX_UPLOAD_BYTES, 10) || 10 * 1024 * 1024;
const SIGNED_URL_TTL_SECONDS = 60;

// Allowed document types (must match the submissions.document_type check constraint)
const DOCUMENT_TYPES = ["OBAS", "TRAVEL_AUTHORITY", "FORM_6"];

// Allowed file types, detected from the file content instead of the client-provided MIME type
const FILE_SIGNATURES = [
  { mimeType: "application/pdf", extension: "pdf", magic: Buffer.from([0x25, 0x50, 0x44, 0x46]) },
  { mimeType: "image/jpeg", extension: "jpg", magic: Buffer.from([0xff, 0xd8, 0xff]) },
  { mimeType: "image/png", extension: "png", magic: Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]) }
];

// Detect the real file type by inspecting the leading bytes of the buffer
const detectFileType = (buffer) => {
  return FILE_SIGNATURES.find((signature) =>
    buffer.length >= signature.magic.length &&
    buffer.subarray(0, signature.magic.length).equals(signature.magic)
  ) || null;
};

// Keep a readable original file name without letting it influence the storage path
const sanitizeFileName = (fileName) => {
  const base = String(fileName || "document").split(/[\\/]/).pop();
  const cleaned = base.replace(/[^\w.\- ]/g, "_").replace(/\s+/g, " ").trim();
  return (cleaned || "document").slice(0, 150);
};

// Build a storage path that is fully generated by the server
const buildStoragePath = (extension) => {
  const now = new Date();
  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, "0");
  return `submissions/${year}/${month}/${crypto.randomUUID()}.${extension}`;
};

// Create a teacher document submission (public, no authentication required)
const createSubmission = async (req, res) => {
  let uploadedPath = null;

  try {
    const teacherName = typeof req.body.teacherName === "string" ? req.body.teacherName.trim() : "";
    const documentType = typeof req.body.documentType === "string" ? req.body.documentType.trim() : "";
    const file = req.file;

    if (!teacherName) {
      return res.status(400).json({
        success: false,
        message: "Full name is required."
      });
    }

    if (teacherName.length < 2 || teacherName.length > 120) {
      return res.status(400).json({
        success: false,
        message: "Full name must be between 2 and 120 characters."
      });
    }

    if (!documentType) {
      return res.status(400).json({
        success: false,
        message: "Document type is required."
      });
    }

    if (!DOCUMENT_TYPES.includes(documentType)) {
      return res.status(400).json({
        success: false,
        message: "Please select a valid document type."
      });
    }

    if (!file || !file.buffer || file.buffer.length === 0) {
      return res.status(400).json({
        success: false,
        message: "Please attach a document to submit."
      });
    }

    if (file.buffer.length > MAX_UPLOAD_BYTES) {
      return res.status(413).json({
        success: false,
        message: `File size exceeds the ${Math.floor(MAX_UPLOAD_BYTES / (1024 * 1024))} MB limit.`
      });
    }

    const detected = detectFileType(file.buffer);

    if (!detected) {
      return res.status(400).json({
        success: false,
        message: "Unsupported file format. Please upload a PDF, JPG, JPEG, or PNG file."
      });
    }

    const storagePath = buildStoragePath(detected.extension);

    const { error: uploadError } = await supabase.storage
      .from(STORAGE_BUCKET)
      .upload(storagePath, file.buffer, {
        contentType: detected.mimeType,
        upsert: false
      });

    if (uploadError) {
      console.error("Submission upload error:", uploadError.message);
      return res.status(500).json({
        success: false,
        message: "We could not upload your document. Please try again."
      });
    }

    uploadedPath = storagePath;

    const { data, error: insertError } = await supabase
      .from("submissions")
      .insert({
        teacher_name: teacherName,
        document_type: documentType,
        original_file_name: sanitizeFileName(file.originalname),
        storage_path: storagePath,
        file_type: detected.mimeType,
        file_size: file.buffer.length
      })
      .select("id, created_at")
      .single();

    if (insertError) {
      console.error("Submission insert error:", insertError.message);

      // Remove the orphaned object so storage stays consistent with the database
      const { error: cleanupError } = await supabase.storage
        .from(STORAGE_BUCKET)
        .remove([uploadedPath]);

      if (cleanupError) {
        console.error("Submission cleanup error:", cleanupError.message);
      }

      return res.status(500).json({
        success: false,
        message: "We could not save your submission. Please try again."
      });
    }

    res.status(201).json({
      success: true,
      message: "Your document has been submitted successfully.",
      data: {
        reference: data.id,
        submittedAt: data.created_at
      }
    });

  } catch (error) {
    console.error("Create submission error:", error.message);
    res.status(500).json({
      success: false,
      message: "An error occurred while submitting your document."
    });
  }
};

// List submissions (administrators only)
const listSubmissions = async (req, res) => {
  try {
    const { data, error } = await supabase
      .from("submissions")
      .select("id, teacher_name, document_type, original_file_name, file_type, file_size, status, created_at")
      .order("created_at", { ascending: false })
      .limit(500);

    if (error) {
      console.error("List submissions error:", error.message);
      return res.status(500).json({
        success: false,
        message: "Unable to load submissions."
      });
    }

    res.json({
      success: true,
      data: data || []
    });

  } catch (error) {
    console.error("List submissions error:", error.message);
    res.status(500).json({
      success: false,
      message: "An error occurred while loading submissions."
    });
  }
};

// Issue a short-lived signed URL for a stored document (administrators only)
const getSubmissionFileUrl = async (req, res) => {
  try {
    const { id } = req.params;
    const download = req.query.download === "true" || req.query.download === "1";

    if (!/^[0-9a-fA-F-]{36}$/.test(id || "")) {
      return res.status(400).json({
        success: false,
        message: "Invalid submission identifier."
      });
    }

    const { data: submission, error: lookupError } = await supabase
      .from("submissions")
      .select("storage_path, original_file_name")
      .eq("id", id)
      .maybeSingle();

    if (lookupError) {
      console.error("Submission lookup error:", lookupError.message);
      return res.status(500).json({
        success: false,
        message: "Unable to load this submission."
      });
    }

    if (!submission) {
      return res.status(404).json({
        success: false,
        message: "Submission not found."
      });
    }

    const { data, error } = await supabase.storage
      .from(STORAGE_BUCKET)
      .createSignedUrl(
        submission.storage_path,
        SIGNED_URL_TTL_SECONDS,
        download ? { download: submission.original_file_name } : undefined
      );

    if (error || !data?.signedUrl) {
      console.error("Signed URL error:", error?.message || "No signed URL returned");
      return res.status(500).json({
        success: false,
        message: "Unable to open this document."
      });
    }

    res.json({
      success: true,
      data: {
        url: data.signedUrl,
        expiresIn: SIGNED_URL_TTL_SECONDS
      }
    });

  } catch (error) {
    console.error("Signed URL error:", error.message);
    res.status(500).json({
      success: false,
      message: "An error occurred while opening the document."
    });
  }
};

module.exports = {
  createSubmission,
  listSubmissions,
  getSubmissionFileUrl,
  DOCUMENT_TYPES,
  MAX_UPLOAD_BYTES,
  STORAGE_BUCKET
};
